services:
  web:
    build:
      context: ./nfstats/
      dockerfile: Dockerfile
      args:
        DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
        DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
        DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
    restart: always
    volumes:
      - ./nfstats:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - /var/flows/:/var/flows/:ro
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgresdb:
  static_volume:
